name: Docker Image CI

on:
  push:
    branches:
      - master   # 推送到 master 分支触发
    tags:
      - v*       # 推送到 v1.2.3 等标签时触发
  pull_request:
    branches:
      - master   # 针对 PR 的操作

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/biliup/caution
          tags: |
            latest
            ${{ github.ref_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Push (skip build)
        run: |
          echo "Verifying login and push permissions..."
          docker tag ghcr.io/biliup/caution:latest ghcr.io/biliup/caution:test
          docker push ghcr.io/biliup/caution:test
