name: Docker Image CI

on:
  push:
    branches:
      - master   # 推送到 master 分支触发
    tags:
      - v*       # 推送到 v1.2.3 等标签时触发
  pull_request:
    branches:
      - master   # 针对 PR 的操作

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 跳过构建步骤，直接验证推送
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 使用 GitHub 用户名
          password: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token

      # 验证推送是否成功
      - name: Test Push to GitHub Container Registry
        run: |
          echo "FROM alpine" > Dockerfile  # 简单的 Dockerfile
          docker build -t ghcr.io/${{ github.repository }}/test:latest .  # 构建镜像
          docker push ghcr.io/${{ github.repository }}/test:latest  # 推送镜像
          
  # 跳过构建步骤，仅验证推送
  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 使用 GitHub 用户名
          password: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token

      - name: Push a simple Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/simple-image:latest .  # 使用简单的镜像标签
          docker push ghcr.io/${{ github.repository }}/simple-image:latest  # 推送镜像
