name: Save Docker Image as Artifact

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  save_image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Check if .version file exists, create if not
        run: |
          if [ ! -f .version ]; then
            echo "1.0.0" > .version  # 如果文件不存在，创建一个默认版本
            echo "Creating .version with default value 1.0.0"
          else
            echo ".version file exists"
          fi

      - name: Read current version
        id: get_version
        run: |
          VERSION=$(cat .version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=old_version::$VERSION"

      - name: Increment version
        id: increment_version
        run: |
          VERSION=$(cat .version)
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$patch"
          echo "$NEW_VERSION" > .version
          echo "::set-output name=new_version::$NEW_VERSION"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Save Docker image as artifact
        run: |
          docker buildx build --platform linux/arm64 -t moonhou/ifcat:${{ env.NEW_VERSION }} . --load
          docker save moonhou/ifcat:${{ env.NEW_VERSION }} -o ifcat-v${{ env.NEW_VERSION }}.tar

      - name: Upload Docker image tar file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ifcat-v${{ env.NEW_VERSION }}.tar
