name: Docker Image CI

on:
  push:
    branches:
      - master   # 推送到 master 分支触发
    tags:
      - v*       # 推送到 v1.2.3 等标签时触发
  pull_request:
    branches:
      - master   # 针对 PR 的操作

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 只验证登录和推送
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 使用 GitHub 用户名
          password: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token

      # 推送镜像到 GitHub Container Registry
      - name: Test Push to GitHub Container Registry
        run: |
          echo "FROM alpine" > Dockerfile  # 创建简单的 Dockerfile
          IMAGE_NAME="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/test:latest"  # 转换为小写
          docker build -t $IMAGE_NAME .  # 构建镜像
          docker push $IMAGE_NAME  # 推送镜像
          
  # 仅验证推送，不进行构建
  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 使用 GitHub 用户名
          password: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token

      - name: Push a simple Docker image
        run: |
          IMAGE_NAME="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/simple-image:latest"  # 转换为小写
          docker build -t $IMAGE_NAME .  # 构建镜像
          docker push $IMAGE_NAME  # 推送镜像
