name: Verify GHCR Login (Hardcoded Token)

on:
  workflow_dispatch:

jobs:
  verify-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: bitm-m
          password: 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

      - name: Verify login by showing Docker info
        run: docker info
