name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 拉取代码

    # 设置 Docker Buildx 环境，以支持多平台构建
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 构建 Docker 镜像
    - name: Build the Docker image for ARM64
      run: |
        docker buildx build . --file Dockerfile --platform linux/arm64 --tag my-image-name:$(date +%s) --load
