name: Upload Docker Image as Artifact (Test)

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Create a dummy Docker image tar file for testing
        run: |
          echo "This is a dummy Docker image tar file" > ifcat-v1.0.0.tar
          echo "Dummy tar file created for upload test."

      - name: Upload dummy Docker image tar file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ifcat-v1.0.0.tar
